/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminAgenda: () => import('#controllers/admin_agenda_controller'),
  AdminAppointments: () => import('#controllers/admin_appointments_controller'),
  AdminAssets: () => import('#controllers/admin_assets_controller'),
  AdminCellules: () => import('#controllers/admin_cellules_controller'),
  AdminDashboard: () => import('#controllers/admin_dashboard_controller'),
  AdminEvents: () => import('#controllers/admin_events_controller'),
  AdminFinances: () => import('#controllers/admin_finances_controller'),
  AdminGaleries: () => import('#controllers/admin_galeries_controller'),
  AdminMedias: () => import('#controllers/admin_medias_controller'),
  AdminMembers: () => import('#controllers/admin_members_controller'),
  AdminMinistries: () => import('#controllers/admin_ministries_controller'),
  AdminNewcomers: () => import('#controllers/admin_newcomers_controller'),
  AdminNewsletter: () => import('#controllers/admin_newsletter_controller'),
  AdminUsers: () => import('#controllers/admin_users_controller'),
  Agenda: () => import('#controllers/agenda_controller'),
  Appointments: () => import('#controllers/appointments_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Cellules: () => import('#controllers/cellules_controller'),
  Contact: () => import('#controllers/contact_controller'),
  Events: () => import('#controllers/events_controller'),
  Galeries: () => import('#controllers/galeries_controller'),
  Home: () => import('#controllers/home_controller'),
  Media: () => import('#controllers/media_controller'),
  Ministries: () => import('#controllers/ministries_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Newsletter: () => import('#controllers/newsletter_controller'),
  Session: () => import('#controllers/session_controller'),
}
