/**
 * Auto-generated by the AdonisJS assembler (Tuyau/Inertia plugin).
 *
 * This file provides a type stub for CI environments and cold builds where the
 * dev server hasn't yet run the assembler hooks. The real file is generated
 * by `node ace serve --hmr` at runtime with the actual shared props types
 * inferred from InertiaMiddleware.share().
 *
 * DO NOT edit this file manually — it will be overwritten by the assembler.
 */

export namespace Data {
  /**
   * Shared props injected by InertiaMiddleware.share() into every Inertia page.
   * Real types are computed at dev-server startup from the middleware class.
   */
  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  export interface SharedProps {}
}
