/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['home']['types'],
  },
  'apropos': {
    methods: ["GET","HEAD"],
    pattern: '/a-propos',
    tokens: [{"old":"/a-propos","type":0,"val":"a-propos","end":""}],
    types: placeholder as Registry['apropos']['types'],
  },
  'media': {
    methods: ["GET","HEAD"],
    pattern: '/media',
    tokens: [{"old":"/media","type":0,"val":"media","end":""}],
    types: placeholder as Registry['media']['types'],
  },
  'gallery': {
    methods: ["GET","HEAD"],
    pattern: '/gallery',
    tokens: [{"old":"/gallery","type":0,"val":"gallery","end":""}],
    types: placeholder as Registry['gallery']['types'],
  },
  'gallery.show': {
    methods: ["GET","HEAD"],
    pattern: '/gallery/:slug',
    tokens: [{"old":"/gallery/:slug","type":0,"val":"gallery","end":""},{"old":"/gallery/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['gallery.show']['types'],
  },
  'allContent': {
    methods: ["GET","HEAD"],
    pattern: '/allContent',
    tokens: [{"old":"/allContent","type":0,"val":"allContent","end":""}],
    types: placeholder as Registry['allContent']['types'],
  },
  'ministries': {
    methods: ["GET","HEAD"],
    pattern: '/ministries',
    tokens: [{"old":"/ministries","type":0,"val":"ministries","end":""}],
    types: placeholder as Registry['ministries']['types'],
  },
  'ministeres.show': {
    methods: ["GET","HEAD"],
    pattern: '/ministeres/:slug',
    tokens: [{"old":"/ministeres/:slug","type":0,"val":"ministeres","end":""},{"old":"/ministeres/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['ministeres.show']['types'],
  },
  'evenements': {
    methods: ["GET","HEAD"],
    pattern: '/evenements',
    tokens: [{"old":"/evenements","type":0,"val":"evenements","end":""}],
    types: placeholder as Registry['evenements']['types'],
  },
  'evenements.detail': {
    methods: ["GET","HEAD"],
    pattern: '/evenements/:slug',
    tokens: [{"old":"/evenements/:slug","type":0,"val":"evenements","end":""},{"old":"/evenements/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['evenements.detail']['types'],
  },
  'agenda': {
    methods: ["GET","HEAD"],
    pattern: '/agenda',
    tokens: [{"old":"/agenda","type":0,"val":"agenda","end":""}],
    types: placeholder as Registry['agenda']['types'],
  },
  'cellules': {
    methods: ["GET","HEAD"],
    pattern: '/cellules',
    tokens: [{"old":"/cellules","type":0,"val":"cellules","end":""}],
    types: placeholder as Registry['cellules']['types'],
  },
  'contact': {
    methods: ["GET","HEAD"],
    pattern: '/contact',
    tokens: [{"old":"/contact","type":0,"val":"contact","end":""}],
    types: placeholder as Registry['contact']['types'],
  },
  'contact.store': {
    methods: ["POST"],
    pattern: '/contact',
    tokens: [{"old":"/contact","type":0,"val":"contact","end":""}],
    types: placeholder as Registry['contact.store']['types'],
  },
  'rendez-vous.index': {
    methods: ["GET","HEAD"],
    pattern: '/rendez-vous',
    tokens: [{"old":"/rendez-vous","type":0,"val":"rendez-vous","end":""}],
    types: placeholder as Registry['rendez-vous.index']['types'],
  },
  'rendez-vous.store': {
    methods: ["POST"],
    pattern: '/rendez-vous',
    tokens: [{"old":"/rendez-vous","type":0,"val":"rendez-vous","end":""}],
    types: placeholder as Registry['rendez-vous.store']['types'],
  },
  'donation': {
    methods: ["GET","HEAD"],
    pattern: '/donation',
    tokens: [{"old":"/donation","type":0,"val":"donation","end":""}],
    types: placeholder as Registry['donation']['types'],
  },
  'intercession': {
    methods: ["GET","HEAD"],
    pattern: '/intercession-priere',
    tokens: [{"old":"/intercession-priere","type":0,"val":"intercession-priere","end":""}],
    types: placeholder as Registry['intercession']['types'],
  },
  'newsletter.store': {
    methods: ["POST"],
    pattern: '/newsletter',
    tokens: [{"old":"/newsletter","type":0,"val":"newsletter","end":""}],
    types: placeholder as Registry['newsletter.store']['types'],
  },
  'newsletter.confirm': {
    methods: ["GET","HEAD"],
    pattern: '/newsletter/confirmer',
    tokens: [{"old":"/newsletter/confirmer","type":0,"val":"newsletter","end":""},{"old":"/newsletter/confirmer","type":0,"val":"confirmer","end":""}],
    types: placeholder as Registry['newsletter.confirm']['types'],
  },
  'login': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['login']['types'],
  },
  'login.store': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['login.store']['types'],
  },
  'auth.verify_email': {
    methods: ["GET","HEAD"],
    pattern: '/verifier-compte/:id',
    tokens: [{"old":"/verifier-compte/:id","type":0,"val":"verifier-compte","end":""},{"old":"/verifier-compte/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['auth.verify_email']['types'],
  },
  'logout': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['logout']['types'],
  },
  'admin.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/admin',
    tokens: [{"old":"/admin","type":0,"val":"admin","end":""}],
    types: placeholder as Registry['admin.dashboard']['types'],
  },
  'admin.users.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.users.index']['types'],
  },
  'admin.users.store': {
    methods: ["POST"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.users.store']['types'],
  },
  'admin.users.update': {
    methods: ["PUT"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.update']['types'],
  },
  'admin.users.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.destroy']['types'],
  },
  'admin.agenda': {
    methods: ["GET","HEAD"],
    pattern: '/admin/agenda',
    tokens: [{"old":"/admin/agenda","type":0,"val":"admin","end":""},{"old":"/admin/agenda","type":0,"val":"agenda","end":""}],
    types: placeholder as Registry['admin.agenda']['types'],
  },
  'admin.agenda.store': {
    methods: ["POST"],
    pattern: '/admin/agenda',
    tokens: [{"old":"/admin/agenda","type":0,"val":"admin","end":""},{"old":"/admin/agenda","type":0,"val":"agenda","end":""}],
    types: placeholder as Registry['admin.agenda.store']['types'],
  },
  'admin.agenda.update': {
    methods: ["PUT"],
    pattern: '/admin/agenda/:id',
    tokens: [{"old":"/admin/agenda/:id","type":0,"val":"admin","end":""},{"old":"/admin/agenda/:id","type":0,"val":"agenda","end":""},{"old":"/admin/agenda/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.agenda.update']['types'],
  },
  'admin.agenda.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/agenda/:id',
    tokens: [{"old":"/admin/agenda/:id","type":0,"val":"admin","end":""},{"old":"/admin/agenda/:id","type":0,"val":"agenda","end":""},{"old":"/admin/agenda/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.agenda.destroy']['types'],
  },
  'admin.agenda.categories.store': {
    methods: ["POST"],
    pattern: '/admin/agenda/categories',
    tokens: [{"old":"/admin/agenda/categories","type":0,"val":"admin","end":""},{"old":"/admin/agenda/categories","type":0,"val":"agenda","end":""},{"old":"/admin/agenda/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin.agenda.categories.store']['types'],
  },
  'admin.agenda.categories.update': {
    methods: ["PUT"],
    pattern: '/admin/agenda/categories/:id',
    tokens: [{"old":"/admin/agenda/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/agenda/categories/:id","type":0,"val":"agenda","end":""},{"old":"/admin/agenda/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/agenda/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.agenda.categories.update']['types'],
  },
  'admin.agenda.categories.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/agenda/categories/:id',
    tokens: [{"old":"/admin/agenda/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/agenda/categories/:id","type":0,"val":"agenda","end":""},{"old":"/admin/agenda/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/agenda/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.agenda.categories.destroy']['types'],
  },
  'admin.assets': {
    methods: ["GET","HEAD"],
    pattern: '/admin/assets',
    tokens: [{"old":"/admin/assets","type":0,"val":"admin","end":""},{"old":"/admin/assets","type":0,"val":"assets","end":""}],
    types: placeholder as Registry['admin.assets']['types'],
  },
  'admin.assets.store': {
    methods: ["POST"],
    pattern: '/admin/assets',
    tokens: [{"old":"/admin/assets","type":0,"val":"admin","end":""},{"old":"/admin/assets","type":0,"val":"assets","end":""}],
    types: placeholder as Registry['admin.assets.store']['types'],
  },
  'admin.assets.activate': {
    methods: ["PATCH"],
    pattern: '/admin/assets/:id/activate',
    tokens: [{"old":"/admin/assets/:id/activate","type":0,"val":"admin","end":""},{"old":"/admin/assets/:id/activate","type":0,"val":"assets","end":""},{"old":"/admin/assets/:id/activate","type":1,"val":"id","end":""},{"old":"/admin/assets/:id/activate","type":0,"val":"activate","end":""}],
    types: placeholder as Registry['admin.assets.activate']['types'],
  },
  'admin.assets.deactivate': {
    methods: ["PATCH"],
    pattern: '/admin/assets/:id/deactivate',
    tokens: [{"old":"/admin/assets/:id/deactivate","type":0,"val":"admin","end":""},{"old":"/admin/assets/:id/deactivate","type":0,"val":"assets","end":""},{"old":"/admin/assets/:id/deactivate","type":1,"val":"id","end":""},{"old":"/admin/assets/:id/deactivate","type":0,"val":"deactivate","end":""}],
    types: placeholder as Registry['admin.assets.deactivate']['types'],
  },
  'admin.assets.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/assets/:id',
    tokens: [{"old":"/admin/assets/:id","type":0,"val":"admin","end":""},{"old":"/admin/assets/:id","type":0,"val":"assets","end":""},{"old":"/admin/assets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.assets.destroy']['types'],
  },
  'admin.evenements': {
    methods: ["GET","HEAD"],
    pattern: '/admin/evenements',
    tokens: [{"old":"/admin/evenements","type":0,"val":"admin","end":""},{"old":"/admin/evenements","type":0,"val":"evenements","end":""}],
    types: placeholder as Registry['admin.evenements']['types'],
  },
  'admin.evenements.store': {
    methods: ["POST"],
    pattern: '/admin/evenements',
    tokens: [{"old":"/admin/evenements","type":0,"val":"admin","end":""},{"old":"/admin/evenements","type":0,"val":"evenements","end":""}],
    types: placeholder as Registry['admin.evenements.store']['types'],
  },
  'admin.evenements.update': {
    methods: ["PUT"],
    pattern: '/admin/evenements/:id',
    tokens: [{"old":"/admin/evenements/:id","type":0,"val":"admin","end":""},{"old":"/admin/evenements/:id","type":0,"val":"evenements","end":""},{"old":"/admin/evenements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.evenements.update']['types'],
  },
  'admin.evenements.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/evenements/:id',
    tokens: [{"old":"/admin/evenements/:id","type":0,"val":"admin","end":""},{"old":"/admin/evenements/:id","type":0,"val":"evenements","end":""},{"old":"/admin/evenements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.evenements.destroy']['types'],
  },
  'admin.evenements.categories.store': {
    methods: ["POST"],
    pattern: '/admin/evenements/categories',
    tokens: [{"old":"/admin/evenements/categories","type":0,"val":"admin","end":""},{"old":"/admin/evenements/categories","type":0,"val":"evenements","end":""},{"old":"/admin/evenements/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin.evenements.categories.store']['types'],
  },
  'admin.evenements.categories.update': {
    methods: ["PUT"],
    pattern: '/admin/evenements/categories/:id',
    tokens: [{"old":"/admin/evenements/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/evenements/categories/:id","type":0,"val":"evenements","end":""},{"old":"/admin/evenements/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/evenements/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.evenements.categories.update']['types'],
  },
  'admin.evenements.categories.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/evenements/categories/:id',
    tokens: [{"old":"/admin/evenements/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/evenements/categories/:id","type":0,"val":"evenements","end":""},{"old":"/admin/evenements/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/evenements/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.evenements.categories.destroy']['types'],
  },
  'admin.medias': {
    methods: ["GET","HEAD"],
    pattern: '/admin/medias',
    tokens: [{"old":"/admin/medias","type":0,"val":"admin","end":""},{"old":"/admin/medias","type":0,"val":"medias","end":""}],
    types: placeholder as Registry['admin.medias']['types'],
  },
  'admin.medias.store': {
    methods: ["POST"],
    pattern: '/admin/medias',
    tokens: [{"old":"/admin/medias","type":0,"val":"admin","end":""},{"old":"/admin/medias","type":0,"val":"medias","end":""}],
    types: placeholder as Registry['admin.medias.store']['types'],
  },
  'admin.medias.update': {
    methods: ["PUT"],
    pattern: '/admin/medias/:id',
    tokens: [{"old":"/admin/medias/:id","type":0,"val":"admin","end":""},{"old":"/admin/medias/:id","type":0,"val":"medias","end":""},{"old":"/admin/medias/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.medias.update']['types'],
  },
  'admin.medias.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/medias/:id',
    tokens: [{"old":"/admin/medias/:id","type":0,"val":"admin","end":""},{"old":"/admin/medias/:id","type":0,"val":"medias","end":""},{"old":"/admin/medias/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.medias.destroy']['types'],
  },
  'admin.medias.categories.store': {
    methods: ["POST"],
    pattern: '/admin/medias/categories',
    tokens: [{"old":"/admin/medias/categories","type":0,"val":"admin","end":""},{"old":"/admin/medias/categories","type":0,"val":"medias","end":""},{"old":"/admin/medias/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin.medias.categories.store']['types'],
  },
  'admin.medias.categories.update': {
    methods: ["PUT"],
    pattern: '/admin/medias/categories/:id',
    tokens: [{"old":"/admin/medias/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/medias/categories/:id","type":0,"val":"medias","end":""},{"old":"/admin/medias/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/medias/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.medias.categories.update']['types'],
  },
  'admin.medias.categories.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/medias/categories/:id',
    tokens: [{"old":"/admin/medias/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/medias/categories/:id","type":0,"val":"medias","end":""},{"old":"/admin/medias/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/medias/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.medias.categories.destroy']['types'],
  },
  'admin.galerie': {
    methods: ["GET","HEAD"],
    pattern: '/admin/galerie',
    tokens: [{"old":"/admin/galerie","type":0,"val":"admin","end":""},{"old":"/admin/galerie","type":0,"val":"galerie","end":""}],
    types: placeholder as Registry['admin.galerie']['types'],
  },
  'admin.galerie.albums.store': {
    methods: ["POST"],
    pattern: '/admin/galerie/albums',
    tokens: [{"old":"/admin/galerie/albums","type":0,"val":"admin","end":""},{"old":"/admin/galerie/albums","type":0,"val":"galerie","end":""},{"old":"/admin/galerie/albums","type":0,"val":"albums","end":""}],
    types: placeholder as Registry['admin.galerie.albums.store']['types'],
  },
  'admin.galerie.albums.update': {
    methods: ["PUT"],
    pattern: '/admin/galerie/albums/:id',
    tokens: [{"old":"/admin/galerie/albums/:id","type":0,"val":"admin","end":""},{"old":"/admin/galerie/albums/:id","type":0,"val":"galerie","end":""},{"old":"/admin/galerie/albums/:id","type":0,"val":"albums","end":""},{"old":"/admin/galerie/albums/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.galerie.albums.update']['types'],
  },
  'admin.galerie.albums.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/galerie/albums/:id',
    tokens: [{"old":"/admin/galerie/albums/:id","type":0,"val":"admin","end":""},{"old":"/admin/galerie/albums/:id","type":0,"val":"galerie","end":""},{"old":"/admin/galerie/albums/:id","type":0,"val":"albums","end":""},{"old":"/admin/galerie/albums/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.galerie.albums.destroy']['types'],
  },
  'admin.galerie.photos.store': {
    methods: ["POST"],
    pattern: '/admin/galerie/photos',
    tokens: [{"old":"/admin/galerie/photos","type":0,"val":"admin","end":""},{"old":"/admin/galerie/photos","type":0,"val":"galerie","end":""},{"old":"/admin/galerie/photos","type":0,"val":"photos","end":""}],
    types: placeholder as Registry['admin.galerie.photos.store']['types'],
  },
  'admin.galerie.photos.update': {
    methods: ["PUT"],
    pattern: '/admin/galerie/photos/:id',
    tokens: [{"old":"/admin/galerie/photos/:id","type":0,"val":"admin","end":""},{"old":"/admin/galerie/photos/:id","type":0,"val":"galerie","end":""},{"old":"/admin/galerie/photos/:id","type":0,"val":"photos","end":""},{"old":"/admin/galerie/photos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.galerie.photos.update']['types'],
  },
  'admin.galerie.photos.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/galerie/photos/:id',
    tokens: [{"old":"/admin/galerie/photos/:id","type":0,"val":"admin","end":""},{"old":"/admin/galerie/photos/:id","type":0,"val":"galerie","end":""},{"old":"/admin/galerie/photos/:id","type":0,"val":"photos","end":""},{"old":"/admin/galerie/photos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.galerie.photos.destroy']['types'],
  },
  'admin.galerie.categories.store': {
    methods: ["POST"],
    pattern: '/admin/galerie/categories',
    tokens: [{"old":"/admin/galerie/categories","type":0,"val":"admin","end":""},{"old":"/admin/galerie/categories","type":0,"val":"galerie","end":""},{"old":"/admin/galerie/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin.galerie.categories.store']['types'],
  },
  'admin.galerie.categories.update': {
    methods: ["PUT"],
    pattern: '/admin/galerie/categories/:id',
    tokens: [{"old":"/admin/galerie/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/galerie/categories/:id","type":0,"val":"galerie","end":""},{"old":"/admin/galerie/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/galerie/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.galerie.categories.update']['types'],
  },
  'admin.galerie.categories.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/galerie/categories/:id',
    tokens: [{"old":"/admin/galerie/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/galerie/categories/:id","type":0,"val":"galerie","end":""},{"old":"/admin/galerie/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/galerie/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.galerie.categories.destroy']['types'],
  },
  'admin.ministeres': {
    methods: ["GET","HEAD"],
    pattern: '/admin/ministeres',
    tokens: [{"old":"/admin/ministeres","type":0,"val":"admin","end":""},{"old":"/admin/ministeres","type":0,"val":"ministeres","end":""}],
    types: placeholder as Registry['admin.ministeres']['types'],
  },
  'admin.ministeres.store': {
    methods: ["POST"],
    pattern: '/admin/ministeres',
    tokens: [{"old":"/admin/ministeres","type":0,"val":"admin","end":""},{"old":"/admin/ministeres","type":0,"val":"ministeres","end":""}],
    types: placeholder as Registry['admin.ministeres.store']['types'],
  },
  'admin.ministeres.update': {
    methods: ["PUT"],
    pattern: '/admin/ministeres/:id',
    tokens: [{"old":"/admin/ministeres/:id","type":0,"val":"admin","end":""},{"old":"/admin/ministeres/:id","type":0,"val":"ministeres","end":""},{"old":"/admin/ministeres/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.ministeres.update']['types'],
  },
  'admin.ministeres.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/ministeres/:id',
    tokens: [{"old":"/admin/ministeres/:id","type":0,"val":"admin","end":""},{"old":"/admin/ministeres/:id","type":0,"val":"ministeres","end":""},{"old":"/admin/ministeres/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.ministeres.destroy']['types'],
  },
  'admin.cellules': {
    methods: ["GET","HEAD"],
    pattern: '/admin/cellules',
    tokens: [{"old":"/admin/cellules","type":0,"val":"admin","end":""},{"old":"/admin/cellules","type":0,"val":"cellules","end":""}],
    types: placeholder as Registry['admin.cellules']['types'],
  },
  'admin.cellules.responsables': {
    methods: ["GET","HEAD"],
    pattern: '/admin/cellules/responsables',
    tokens: [{"old":"/admin/cellules/responsables","type":0,"val":"admin","end":""},{"old":"/admin/cellules/responsables","type":0,"val":"cellules","end":""},{"old":"/admin/cellules/responsables","type":0,"val":"responsables","end":""}],
    types: placeholder as Registry['admin.cellules.responsables']['types'],
  },
  'admin.cellules.store': {
    methods: ["POST"],
    pattern: '/admin/cellules',
    tokens: [{"old":"/admin/cellules","type":0,"val":"admin","end":""},{"old":"/admin/cellules","type":0,"val":"cellules","end":""}],
    types: placeholder as Registry['admin.cellules.store']['types'],
  },
  'admin.cellules.update': {
    methods: ["PUT"],
    pattern: '/admin/cellules/:id',
    tokens: [{"old":"/admin/cellules/:id","type":0,"val":"admin","end":""},{"old":"/admin/cellules/:id","type":0,"val":"cellules","end":""},{"old":"/admin/cellules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.cellules.update']['types'],
  },
  'admin.cellules.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/cellules/:id',
    tokens: [{"old":"/admin/cellules/:id","type":0,"val":"admin","end":""},{"old":"/admin/cellules/:id","type":0,"val":"cellules","end":""},{"old":"/admin/cellules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.cellules.destroy']['types'],
  },
  'admin.newsletter': {
    methods: ["GET","HEAD"],
    pattern: '/admin/newsletter',
    tokens: [{"old":"/admin/newsletter","type":0,"val":"admin","end":""},{"old":"/admin/newsletter","type":0,"val":"newsletter","end":""}],
    types: placeholder as Registry['admin.newsletter']['types'],
  },
  'admin.newsletter.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/newsletter/:id',
    tokens: [{"old":"/admin/newsletter/:id","type":0,"val":"admin","end":""},{"old":"/admin/newsletter/:id","type":0,"val":"newsletter","end":""},{"old":"/admin/newsletter/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.newsletter.destroy']['types'],
  },
  'admin.membres.print': {
    methods: ["GET","HEAD"],
    pattern: '/admin/membres/print',
    tokens: [{"old":"/admin/membres/print","type":0,"val":"admin","end":""},{"old":"/admin/membres/print","type":0,"val":"membres","end":""},{"old":"/admin/membres/print","type":0,"val":"print","end":""}],
    types: placeholder as Registry['admin.membres.print']['types'],
  },
  'admin.membres': {
    methods: ["GET","HEAD"],
    pattern: '/admin/membres',
    tokens: [{"old":"/admin/membres","type":0,"val":"admin","end":""},{"old":"/admin/membres","type":0,"val":"membres","end":""}],
    types: placeholder as Registry['admin.membres']['types'],
  },
  'admin.members.store': {
    methods: ["POST"],
    pattern: '/admin/members',
    tokens: [{"old":"/admin/members","type":0,"val":"admin","end":""},{"old":"/admin/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['admin.members.store']['types'],
  },
  'admin.members.update': {
    methods: ["PUT"],
    pattern: '/admin/members/:id',
    tokens: [{"old":"/admin/members/:id","type":0,"val":"admin","end":""},{"old":"/admin/members/:id","type":0,"val":"members","end":""},{"old":"/admin/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.members.update']['types'],
  },
  'admin.members.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/members/:id',
    tokens: [{"old":"/admin/members/:id","type":0,"val":"admin","end":""},{"old":"/admin/members/:id","type":0,"val":"members","end":""},{"old":"/admin/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.members.destroy']['types'],
  },
  'admin.rendez-vous': {
    methods: ["GET","HEAD"],
    pattern: '/admin/rendez-vous',
    tokens: [{"old":"/admin/rendez-vous","type":0,"val":"admin","end":""},{"old":"/admin/rendez-vous","type":0,"val":"rendez-vous","end":""}],
    types: placeholder as Registry['admin.rendez-vous']['types'],
  },
  'admin.rendez-vous.print': {
    methods: ["GET","HEAD"],
    pattern: '/admin/rendez-vous/print',
    tokens: [{"old":"/admin/rendez-vous/print","type":0,"val":"admin","end":""},{"old":"/admin/rendez-vous/print","type":0,"val":"rendez-vous","end":""},{"old":"/admin/rendez-vous/print","type":0,"val":"print","end":""}],
    types: placeholder as Registry['admin.rendez-vous.print']['types'],
  },
  'admin.rendez-vous.update': {
    methods: ["PUT"],
    pattern: '/admin/rendez-vous/:id',
    tokens: [{"old":"/admin/rendez-vous/:id","type":0,"val":"admin","end":""},{"old":"/admin/rendez-vous/:id","type":0,"val":"rendez-vous","end":""},{"old":"/admin/rendez-vous/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.rendez-vous.update']['types'],
  },
  'admin.rendez-vous.reschedule': {
    methods: ["PATCH"],
    pattern: '/admin/rendez-vous/:id/reschedule',
    tokens: [{"old":"/admin/rendez-vous/:id/reschedule","type":0,"val":"admin","end":""},{"old":"/admin/rendez-vous/:id/reschedule","type":0,"val":"rendez-vous","end":""},{"old":"/admin/rendez-vous/:id/reschedule","type":1,"val":"id","end":""},{"old":"/admin/rendez-vous/:id/reschedule","type":0,"val":"reschedule","end":""}],
    types: placeholder as Registry['admin.rendez-vous.reschedule']['types'],
  },
  'admin.rendez-vous.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/rendez-vous/:id',
    tokens: [{"old":"/admin/rendez-vous/:id","type":0,"val":"admin","end":""},{"old":"/admin/rendez-vous/:id","type":0,"val":"rendez-vous","end":""},{"old":"/admin/rendez-vous/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.rendez-vous.destroy']['types'],
  },
  'admin.nouveaux_venus.print': {
    methods: ["GET","HEAD"],
    pattern: '/admin/nouveaux-venus/print',
    tokens: [{"old":"/admin/nouveaux-venus/print","type":0,"val":"admin","end":""},{"old":"/admin/nouveaux-venus/print","type":0,"val":"nouveaux-venus","end":""},{"old":"/admin/nouveaux-venus/print","type":0,"val":"print","end":""}],
    types: placeholder as Registry['admin.nouveaux_venus.print']['types'],
  },
  'admin.nouveaux_venus': {
    methods: ["GET","HEAD"],
    pattern: '/admin/nouveaux-venus',
    tokens: [{"old":"/admin/nouveaux-venus","type":0,"val":"admin","end":""},{"old":"/admin/nouveaux-venus","type":0,"val":"nouveaux-venus","end":""}],
    types: placeholder as Registry['admin.nouveaux_venus']['types'],
  },
  'admin.newcomers.store': {
    methods: ["POST"],
    pattern: '/admin/newcomers',
    tokens: [{"old":"/admin/newcomers","type":0,"val":"admin","end":""},{"old":"/admin/newcomers","type":0,"val":"newcomers","end":""}],
    types: placeholder as Registry['admin.newcomers.store']['types'],
  },
  'admin.newcomers.update': {
    methods: ["PUT"],
    pattern: '/admin/newcomers/:id',
    tokens: [{"old":"/admin/newcomers/:id","type":0,"val":"admin","end":""},{"old":"/admin/newcomers/:id","type":0,"val":"newcomers","end":""},{"old":"/admin/newcomers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.newcomers.update']['types'],
  },
  'admin.newcomers.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/newcomers/:id',
    tokens: [{"old":"/admin/newcomers/:id","type":0,"val":"admin","end":""},{"old":"/admin/newcomers/:id","type":0,"val":"newcomers","end":""},{"old":"/admin/newcomers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.newcomers.destroy']['types'],
  },
  'admin.finances': {
    methods: ["GET","HEAD"],
    pattern: '/admin/finances',
    tokens: [{"old":"/admin/finances","type":0,"val":"admin","end":""},{"old":"/admin/finances","type":0,"val":"finances","end":""}],
    types: placeholder as Registry['admin.finances']['types'],
  },
  'admin.finances.operations.store': {
    methods: ["POST"],
    pattern: '/admin/finances/operations',
    tokens: [{"old":"/admin/finances/operations","type":0,"val":"admin","end":""},{"old":"/admin/finances/operations","type":0,"val":"finances","end":""},{"old":"/admin/finances/operations","type":0,"val":"operations","end":""}],
    types: placeholder as Registry['admin.finances.operations.store']['types'],
  },
  'admin.finances.operations.update': {
    methods: ["PUT"],
    pattern: '/admin/finances/operations/:id',
    tokens: [{"old":"/admin/finances/operations/:id","type":0,"val":"admin","end":""},{"old":"/admin/finances/operations/:id","type":0,"val":"finances","end":""},{"old":"/admin/finances/operations/:id","type":0,"val":"operations","end":""},{"old":"/admin/finances/operations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.finances.operations.update']['types'],
  },
  'admin.finances.operations.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/finances/operations/:id',
    tokens: [{"old":"/admin/finances/operations/:id","type":0,"val":"admin","end":""},{"old":"/admin/finances/operations/:id","type":0,"val":"finances","end":""},{"old":"/admin/finances/operations/:id","type":0,"val":"operations","end":""},{"old":"/admin/finances/operations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.finances.operations.destroy']['types'],
  },
  'admin.finances.categories.store': {
    methods: ["POST"],
    pattern: '/admin/finances/categories',
    tokens: [{"old":"/admin/finances/categories","type":0,"val":"admin","end":""},{"old":"/admin/finances/categories","type":0,"val":"finances","end":""},{"old":"/admin/finances/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin.finances.categories.store']['types'],
  },
  'admin.finances.categories.update': {
    methods: ["PUT"],
    pattern: '/admin/finances/categories/:id',
    tokens: [{"old":"/admin/finances/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/finances/categories/:id","type":0,"val":"finances","end":""},{"old":"/admin/finances/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/finances/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.finances.categories.update']['types'],
  },
  'admin.finances.categories.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/finances/categories/:id',
    tokens: [{"old":"/admin/finances/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/finances/categories/:id","type":0,"val":"finances","end":""},{"old":"/admin/finances/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/finances/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.finances.categories.destroy']['types'],
  },
  'admin.finances.rates.update': {
    methods: ["POST"],
    pattern: '/admin/finances/rates',
    tokens: [{"old":"/admin/finances/rates","type":0,"val":"admin","end":""},{"old":"/admin/finances/rates","type":0,"val":"finances","end":""},{"old":"/admin/finances/rates","type":0,"val":"rates","end":""}],
    types: placeholder as Registry['admin.finances.rates.update']['types'],
  },
  'admin.donations': {
    methods: ["GET","HEAD"],
    pattern: '/admin/donations',
    tokens: [{"old":"/admin/donations","type":0,"val":"admin","end":""},{"old":"/admin/donations","type":0,"val":"donations","end":""}],
    types: placeholder as Registry['admin.donations']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
